palabra = 'Una palabra'
print(palabra)
lista = list(palabra)
print(lista)
diccionario = {'nombre': 'Eider', 'Apellido': 'Cruz'}
lista = list(diccionario.keys())
lista = list(diccionario.values())
# lista = list(diccionario.items())
print(lista)
tupla = tuple(lista)
print(tupla)
lista = list(palabra)
print(dict(lista))
palabra = ''.join(lista)
print(palabra)