nota1=float(input("Ingrese la primera nota: "))
nota2=float(input("Ingrese la segunda nota: "))
nota3=float(input("Ingrese la tercer nota: "))
promedio=float((nota1+nota2+nota3)/3)
print("Su promedio es: "+str(promedio))